use swiggy;

-- 1. SELECT all records from the restaurants table.
SELECT * FROM restaurants;

-- 2. Rank every restaurant from most expensive to least expensive.
SELECT *,RANK() OVER(ORDER BY cost DESC) as 'rank' FROM restaurants;

-- 3. Rank every restaurant from most visited to least visited.
SELECT *,RANK() OVER(ORDER BY rating_count DESC) as 'rank' FROM restaurants;

-- 4. Rank every restaurant from most expensive to least expensive as per their city.
SELECT *,RANK() OVER(PARTITION BY city ORDER BY cost DESC) as 'rank' FROM restaurants;

-- 5. Dense-rank every restaurant from highest to lowest rated as per their city.
SELECT *,DENSE_RANK() OVER(PARTITION BY city ORDER BY rating DESC) as 'rank' FROM restaurants;

-- 6. Row-number every restaurant from most expensive to least expensive as per their city.
SELECT *,ROW_NUMBER() OVER(PARTITION BY city ORDER BY cost DESC) as 'rank' FROM restaurants;

-- 7. Rank the restaurant based on their prices (most to least expensive) as per cuisine using rank, dense_rank, and row_number.
SELECT *,
RANK() OVER(PARTITION BY cuisine ORDER BY cost DESC) as 'rank',
DENSE_RANK() OVER(PARTITION BY cuisine ORDER BY cost DESC) as 'dense_rank',
ROW_NUMBER() OVER(PARTITION BY cuisine ORDER BY cost DESC) as 'row_number'
FROM restaurants;

-- 8. Find top 5 restaurants of every city as per their revenue.
SELECT t.name,t.city,t.revenue,t.rank FROM (
SELECT *,cost*rating_count as revenue, 
DENSE_RANK() OVER(PARTITION BY city ORDER BY (cost*rating_count) DESC) as 'rank' 
FROM restaurants) t
WHERE t.rank<=5;

-- 9. Find top 5 restaurants of every cuisine as per their revenue.
SELECT t.name,t.cuisine,t.revenue,t.rank FROM (
SELECT *,cost*rating_count as revenue, 
DENSE_RANK() OVER(PARTITION BY cuisine ORDER BY (cost*rating_count) DESC) as 'rank' 
FROM restaurants) t
WHERE t.rank<=5;

-- 10. List the top 5 cuisines as per the revenue generated by top 5 restaurants of every cuisine.
SELECT t.cuisine,SUM(t.revenue) as total_revenue FROM (
SELECT *,cost*rating_count as revenue, 
DENSE_RANK() OVER(PARTITION BY cuisine ORDER BY (cost*rating_count) DESC) as 'rank' 
FROM restaurants) t
WHERE t.rank<=5
GROUP BY t.cuisine
ORDER BY total_revenue DESC LIMIT 5;

-- 11. List the top 5 cities as per the revenue generated by top 5 restaurants of every city.
SELECT t.city, SUM(t.revenue) as total_revenue FROM (
SELECT *,cost*rating_count as revenue, 
DENSE_RANK() OVER(PARTITION BY city ORDER BY (cost*rating_count) DESC) as 'rank' 
FROM restaurants) t
WHERE t.rank<=5
GROUP BY t.city
ORDER BY total_revenue DESC LIMIT 5;

-- 12. Find the total revenue generated by top 1% restaurants.
SELECT SUM(t.revenue) as 'total_revenue_by_top_1%' FROM (
SELECT *, cost*rating_count as 'revenue', row_number() over(ORDER BY cost*rating_count DESC) as 'rank' 
FROM restaurants) t
WHERE t.rank <= ((SELECT count(*) FROM restaurants)/100);

-- 13. Find the total revenue generated by top 20% restaurants.
SELECT SUM(t.revenue) as 'total_revenue_by_top_20%' FROM (
SELECT *, cost*rating_count as 'revenue', row_number() over(ORDER BY cost*rating_count DESC) as 'rank' 
FROM restaurants) t
WHERE t.rank <= ((SELECT count(*) FROM restaurants)*0.2);

-- 14. What percentage of total revenue is generated by top 20% restaurants?
with 
   q1 as (
    SELECT SUM(t.revenue) as 'total_revenue_by_top_20_percent' FROM (
	SELECT *, cost*rating_count as 'revenue', row_number() over(ORDER BY cost*rating_count DESC) as 'rank' 
	FROM restaurants) t
	WHERE t.rank <= ((SELECT count(*) FROM restaurants)*0.2)),
   q2 as (
    SELECT SUM(cost*rating_count) as 'total_revenue' FROM restaurants)

SELECT (total_revenue_by_top_20_percent/total_revenue)*100 as '%revenue' FROM q1,q2;